server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: security-client
  grpc:
    server:
      enabled: false
    client:
      channels:
        platform-server:
          address: ${PLATFORM_GRPC_URL:localhost:9090}
          enable-keep-alive: true
          keep-alive-time: 30s
          keep-alive-timeout: 5s
          max-inbound-message-size: 20MB
  security:
    oauth2:
      client:
        registration:
          grpc-client:
            provider: as-vina
            client-id: ${GRPC_CLIENT_ID:grpc-client}
            client-secret: ${GRPC_CLIENT_SECRET:grpc-secret}
            authorization-grant-type: client_credentials
            scope:
              - "api.read"
              - "api.write"
        provider:
          as-vina:
            token-uri: ${AS_VINA_TOKEN_URI:http://localhost:8080/oauth2/token}
springdoc:
  swagger-ui:
    path: /
    operations-sorter: method
logging:
  level:
    root: INFO
    vn:
      vinaacademy:
        security: TRACE